### ISSUE TITLE
TODO: fix formatting of pytest.md

### ISSUE THREAD

**Issue by floer32** [hangtwenty/python-is-for-lovers#1]

**Comment by ArionMiles** [comment]
If this issue is still up, can you tell me what needs fixing? I'll be happy to do it.

**Comment by floer32** [comment]
Thanks for reminding me this was still open, it was a quickie so I just did it. There are some other issues to add some more stuff like links to other getting-started guides, feel free to pick one of those up and submit a PR. Some of them have notes to get started.
