### ISSUE TITLE
Practice web sites and mobile apps references

### ISSUE THREAD

**Issue by akiselev1** [hangtwenty/python-is-for-lovers#17]
Hello! 
I found this collection of Python learning resources really useful at my level (beginner-intermediate) and added a star immediately.

 May I propose a couple of additions? 
1. "Practice makes perfect" section with a few links to top 3 python-friendly free coding challenges web sites (like hackerrank.com, for example).
2. Mobile app section. My personal favorite is SoloLearn Android app with Python 3 tutorial.
 
Please let me know it makes sense to you, or already covered elsewhere.  I can open a PR with proposed changes.

**Comment by floer32** [comment]
@akiselev1 I appreciate the ideas! I don't think they fit in this Python-specific guide. But, I would encourage you to check out the Awesome List of Awesome Lists :) https://github.com/sindresorhus/awesome

There, you'll find many more resources, and you'll find themes like mobile or coding challenge websites. The PRs you mentioned will surely fit at least one list. Thanks again!
